// subject enums
export enum Subjects {
    UserCreated = 'vacepay.prod.user.created',
    UserUpdated = 'vacepay.prod.user.updated',
    UserDeleted = 'vacepay.prod.user.deleted',
    CountryFound = 'vacepay.prod.country.found',
    LocationSaved = 'vacepay.prod.location.saved',
    NotificationCreated = 'vacepay.prod.notification.created',
    NotificationUpdated = 'vacepay.prod.notification.updated',
    NotificationDeleted = 'vacepay.prod.notification.deleted',
    AuditCreated = 'vacepay.prod.audit.created',
    AuditUpdated = 'vacepay.prod.audit.updated',
    AuditDeleted = 'vacepay.prod.audit.deleted',
    KYCCreated = 'vacepay.prod.kyc.created',
    KYCUpdated = 'vacepay.prod.kyc.updated',
    AssetCreated = 'vacepay.prod.asset.created',
    AssetUpdated = 'vacepay.prod.asset.updated',
    AssetDeleted = 'vacepay.prod.asset.deleted',
    BankCreated = 'vacepay.prod.bank.created',
    BankUpdated = 'vacepay.prod.bank.updated',
    BankDeleted = 'vacepay.prod.bank.deleted',
    CoinCreated = 'vacepay.prod.coin.created',
    CoinUpdated = 'vacepay.prod.coin.updated',
    CoinDeleted = 'vacepay.prod.coin.deleted',
    LanguageCreated = 'vacepay.prod.lang.created',
    LanguageUpdated = 'vacepay.prod.lang.updated',
    LanguageDeleted = 'vacepay.prod.lang.deleted',
    ComplianceUpdated = 'vacepay.prod.compliance.updated'
}

export enum STGSubjects {
    UserCreated = 'vacepay.staging.user.created',
    UserUpdated = 'vacepay.staging.user.updated',
    UserDeleted = 'vacepay.staging.user.deleted',
    CountryFound = 'vacepay.staging.country.found',
    LocationSaved = 'vacepay.staging.location.saved',
    NotificationCreated = 'vacepay.staging.notification.created',
    NotificationUpdated = 'vacepay.staging.notification.updated',
    NotificationDeleted = 'vacepay.staging.notification.deleted',
    AuditCreated = 'vacepay.staging.audit.created',
    AuditUpdated = 'vacepay.staging.audit.updated',
    AuditDeleted = 'vacepay.staging.audit.deleted',
    KYCCreated = 'vacepay.staging.kyc.created',
    KYCUpdated = 'vacepay.staging.kyc.updated',
    AssetCreated = 'vacepay.staging.asset.created',
    AssetUpdated = 'vacepay.staging.asset.updated',
    AssetDeleted = 'vacepay.staging.asset.deleted',
    BankCreated = 'vacepay.staging.bank.created',
    BankUpdated = 'vacepay.staging.bank.updated',
    BankDeleted = 'vacepay.staging.bank.deleted',
    CoinCreated = 'vacepay.staging.coin.created',
    CoinUpdated = 'vacepay.staging.coin.updated',
    CoinDeleted = 'vacepay.staging.coin.deleted',
    LanguageCreated = 'vacepay.staging.lang.created',
    LanguageUpdated = 'vacepay.staging.lang.updated',
    LanguageDeleted = 'vacepay.staging.lang.deleted',
    ComplianceUpdated = 'vacepay.staging.compliance.updated'
}

export enum DEVSubjects {
    UserCreated = 'vacepay.development.user.created',
    UserUpdated = 'vacepay.development.user.updated',
    UserDeleted = 'vacepay.development.user.deleted',
    CountryFound = 'vacepay.development.country.found',
    LocationSaved = 'vacepay.development.location.saved',
    NotificationCreated = 'vacepay.development.notification.created',
    NotificationUpdated = 'vacepay.development.notification.updated',
    NotificationDeleted = 'vacepay.development.notification.deleted',
    AuditCreated = 'vacepay.development.audit.created',
    AuditUpdated = 'vacepay.development.audit.updated',
    AuditDeleted = 'vacepay.development.audit.deleted',
    KYCCreated = 'vacepay.development.kyc.created',
    KYCUpdated = 'vacepay.development.kyc.updated',
    AssetCreated = 'vacepay.development.asset.created',
    AssetUpdated = 'vacepay.development.asset.updated',
    AssetDeleted = 'vacepay.development.asset.deleted',
    BankCreated = 'vacepay.development.bank.created',
    BankUpdated = 'vacepay.development.bank.updated',
    BankDeleted = 'vacepay.development.bank.deleted',
    CoinCreated = 'vacepay.development.coin.created',
    CoinUpdated = 'vacepay.development.coin.updated',
    CoinDeleted = 'vacepay.development.coin.deleted',
    LanguageCreated = 'vacepay.development.lang.created',
    LanguageUpdated = 'vacepay.development.lang.updated',
    LanguageDeleted = 'vacepay.development.lang.deleted',
    ComplianceUpdated = 'vacepay.development.compliance.updated'
}